/*
 * state_machine_type.h
 *
 *  Created on: Jan 6, 2026
 *      Author: Owner
 */

#ifndef STATE_MACHINE_TYPE_H_
#define STATE_MACHINE_TYPE_H_
#include <stdint.h>

typedef enum
{
	MAIN_STATE_SYSTEM_INIT,
	MAIN_STATE_PASS_INPUT,
	MAIN_STATE_STANDBY,
	MAIN_STATE_IDLE,
	MAIN_STATE_ERROR,
	MAIN_STATE_EXPOSURE,
	MAIN_STATE_CONFIGURE,
	MAIN_STATE_DUTYWAIT,
	MAIN_STATE_BATTMGMT,
}main_state_t;


typedef enum
{
	SUB_STATE_PASS_INPUT_INIT,
	SUB_STATE_PASS_INPUT_PASS_WAIT,
	SUB_STATE_PASS_INPUT_PASS_CHECK,
	SUB_STATE_PASS_INPUT_PASS_SUCCESS,
}sub_state_pass_input_t;

typedef enum
{
	SUB_STATE_STANDBY_INIT,
	SUB_STATE_STANDBY_SETUP,
	SUB_STATE_STANDBY_READY,
	SUB_STATE_STANDBY_ENTER_LOCK,
	SUB_STATE_STANDBY_HOLD_EXPOSURE_BUTTON,
	SUB_STATE_STANDBY_ENTER_POWER_SAVE,
	SUB_STATE_STANDBY_RETURN_FROM_EXPOSURE,
}sub_state_standby_t;

typedef enum
{
	SUB_STATE_ERROR_INIT,
	SUB_STATE_ERROR_SET_UI,
	SUB_STATE_ERROR_WAIT,
	SUB_STATE_ERROR_EXIT,

}sub_state_error_t;

typedef enum
{
	SUB_STATE_DUTY_WAIT_INIT,
	SUB_STATE_DUTY_WAIT_WAIT,
	SUB_STATE_DUTY_WAIT_DISPLAY_TIME,
	SUB_STATE_DUTY_WAIT_DISPLAY_WARNING,
	SUB_STATE_DUTY_WAIT_WAIT_DONE,
}sub_state_duty_wait_t;

typedef enum
{
	SUB_STATE_BATTMGMT_INIT,
	SUB_STATE_BATTMGMT_HOLD_BATT_LOW,
	SUB_STATE_BATTMGMT_START_CHARGE,
	SUB_STATE_BATTMGMT_CHARGE,
	SUB_STATE_BATTMGMT_EXIT_CHARGE_TO_STANDBY,
	SUB_STATE_BATTMGMT_START_CHARGE_FROM_PASS_INPUT,
	SUB_STATE_BATTMGMT_CHARGE_FROM_PASS_INPUT,
	SUB_STATE_BATTMGMT_EXIT_CHARGE_TO_PASS_INPUT,
}sub_state_battmgmt_t;

typedef struct
{
	uint32_t main_state;
	uint32_t sub_state;
}state_machine_t;


void SetMainState(main_state_t mainState);
uint32_t GetMainState();
void SetSubState(main_state_t subState);
uint32_t GetSubState();
#endif /* STATE_MACHINE_H_ */
